### ISSUE TITLE
Unable to get multiselect working

### ISSUE THREAD

**Issue by damogallagher** [networknt/angular-schema-form-ui-select#1]
I have been able to use this plugin to get a single select working but unable to get the equivalent multi select working unfortunately.
I can get the selected value for the single select form and it shows correctly but I cannot for the life of me get the value in the multi select form

Is there anything obvious with my schema and form that may cause this to not be working?
{
  schema: {
    type: 'object',
    title: 'Select',
    properties: {
		instanceIds: {
	        title: 'Instance Ids',
	  		placeholder: 'Select Instance Ids', 	        
	        type: 'array',
	        format: 'uiselect',
	        minItems: '1',
	        items: [
          { value: 'one', label: 'label1'},
          { value: 'two', label: 'label2'},
          { value: 'three', label: 'label3'},
          { value: 'four', label: 'label4'},
          { value: 'five', label: 'label5'}
        ]
	      }
     },
      required: ['instanceIds']
  },
  form: [
  	{
  	  key: 'instanceIds',
	  options: {
	    uiClass: 'short_select'
	  }
	}
  ]
}

**Comment by stevehu** [comment]
I am glad to hear someone is using it. Yes. There is a bug for multiple if
no default value has been selected and I am trying to fix it but it is
lowest priority for me for now:) I am using strapselect for multiple at the
moment.

Thanks,

Steve

**Comment by damogallagher** [comment]
Thanks for getting back to me Steve

Thats good to know - saves me alot of grief :)
Would you recommend strap select for single and multi select over this plugin?

**Comment by stevehu** [comment]
Strapselect for multiple only as it is not as powerful as uiselect.

**Comment by damogallagher** [comment]
perfect, thanks Steve

**Comment by damogallagher** [comment]
Hi Steve

1 last question Sorry

I am using your plugin now successfully but ran into 1 issue with a single
selcet form
Take the following form
{
  "schema": {
    "type": "object",
    "title": "Tag",
    "properties": {
      "tagName":  {
        "title": "Tag Name",
        "placeholder": "Select Tag Name",
"type": "string",
    "format": "uiselect",
    "items": []
      },
      "tagValue":  {
        "title": "Tag Value",
        "placeholder": "Select Tag Value",
"type": "string",
    "format": "uiselect",
    "items": []
      }
    },
    "required": ["tagName", "tagValue"]
  },
  "form": [
  {
    "key" : "tagName",
      "onChange": "tagValueUpdated(modelValue,form)"
    },
    {
    "key" : "tagValue"
    }

  ]
}


When I go to edit an existing form element - i pull my data from a
webservice
However when i load the form, i am not able to set the current default value

Here is my javascript
                    $http.get(templateURL).then(function(response){
                        $scope.schema = response.data.schema;
                        $scope.schema.properties.tagName.items =
tagNameItems;
                        $scope.schema.properties.tagValue.items = [];
                        $scope.form   = response.data.form;

                        //if (resetModelData) {
                         //$scope.modelData = response.data.model || {};
                            $scope.modelData =
JSON.parse($scope.userTask.taskDetails) || {};
                            $scope.schema.properties.tagName.value =
$scope.modelData.tagName;
                            alert("1
$scope.modelData:"+$scope.modelData.tagName);
                       // }
                      });

Any idea what I need to do to set the selected tagName and tagValue when  I
choose edit?

This is the only piece that is causing me difficulty at the minute

Thank you
Damien

**Comment by stevehu** [comment]
I had the same problem before and I pre-processed the my form on my server
to populate the items for both strapselect and uiselect. dynamically
loading data from server only works for strapselect and I have a couple of
examples in light repo. Thanks.

**Comment by damogallagher** [comment]
so with the requirement to use single select forms and multi select forms -
you would recommend to use strap select and forget about uiselect?

**Comment by stevehu** [comment]
Yes. Use strapselect for now until uiselect is fixed. Thanks.

**Comment by stevehu** [comment]
@damogallagher With help from @strets123 the ui-select is fixed and has all the feature of strapselect. You can use uiselect from master head for now and I will release it in a week or two. @strets123 also added tag, group by, search by description features. Thanks.

**Comment by damogallagher** [comment]
Thats fantastic, excellent work on this guys

**Comment by stevehu** [comment]
Forgot to mention that I have merged code from @nicklasb on strapselect to uiselect so all the remote callbacks/post/get are working on my local but pending to update URLs to my production server. Thanks @nicklasb for your contributions.

**Comment by damogallagher** [comment]
Hi

Just wanted to follow up on this as I have only had a chance to get back to this feature in my application now.
@stevehu - angular schema form ui select is now working perfectly in my application for all use cases I have. I have dropdowns with single select and dropdowns with multiselect and it works perfectly.
All of my schema forms are also loaded dynamically based on a value selected by a user and your plugin works perfectly for creating new items and updating existing items

Overall I am extremely satisfied with this plugin and the fixes you put in recently are fantastic. Well done on a great job and I hope this plugin starts to gain traction as its fantastic

Cheers
Damien
