### ISSUE TITLE
Not able to use this plugin in angular-schema-form

### ISSUE THREAD

**Issue by stephenbaidu** [networknt/angular-schema-form-ui-select#16]
On using bower to install, am not able to use this plugin. I even included the `schema-form-strapselect.js` and still nothing shows up. By the way, do we really need `strapselect` to use ui-select? Can I please get a link to a working demo. Thanks.

**Comment by stephenbaidu** [comment]
Also, won't it be nice to just drop in this plugin and have it work with the default select's `titleMap` in the form definition instead (or as well as) of `items` in the schema definition.

**Comment by stevehu** [comment]
I would recommend using angular-schema-form-uiselect. Once you have installed npm modules and bower components, you can run gulp webserver to start the demo.

**Comment by stephenbaidu** [comment]
Thanks @stevehu, I've been able to do that you recommend but it is not ui-select. I want angular-ui-select.

**Comment by stephenbaidu** [comment]
My bad. It is ui-select and it's working. But there's one error that keeps popping up in the console `Unknown provider: whereFilterProvider <- whereFilter` that am trying to resolve. Thanks again.

**Comment by benoror** [comment]
See https://github.com/networknt/angular-schema-form-ui-select/issues/7

**Comment by stephenbaidu** [comment]
Thanks @benoror
