### ISSUE TITLE
Setting focus when form renders

### ISSUE THREAD

**Issue by connect-dips** [networknt/angular-schema-form-ui-select#23]
Is it possible to set focus on the ui-select and open the dropdown when the form completes rendering? I tried few angular and jquery methods without success. Please advise.

Thanks.

**Comment by stevehu** [comment]
@connect-dips I had used Angular 1.x for a while and switched to React later on. These Angular schema form components are no long maintained. There are based on Angular 1.x and if you are using Angular 2 or newer version, please take a look at https://github.com/json-schema-form/angular-schema-form
