### ISSUE TITLE
multiselect values are not in the model if there is no default value

### ISSUE THREAD

**Issue by stevehu** [networknt/angular-schema-form-ui-select#3]
There is a bug in multiselect that model is not populated from selected multiselect field. If there is default value available for the field,then it is working and you can add or remove items. When all items are removed an empty array will be in the model. if there is no default value, the array is not created in model. This is a show stopper for multiselect and I am using strapselect for multiple select now until it is fixed.

**Comment by strets123** [comment]
Thank you for the suggestion, it was not that difficult as you say.

I have made a pull request to the upstream project which fixes this issue for all array type fields. Cheers, Andy.

https://github.com/Textalk/angular-schema-form/pull/296

**Comment by stevehu** [comment]
@strets123 Thans a lot for the fix. It works and now the directive support fetch from API server for the dropdowns and I will switch the URLs to my production server when I release it.
