### ISSUE TITLE
Unknown providers: translateFilterProvider, highlightFilterProvider, whereFilterProvider

### ISSUE THREAD

**Issue by benoror** [networknt/angular-schema-form-ui-select#7]
**Fixed: translateFilterProvider**

After figuring out I had to inject `'pascalprecht.translate'`  as a dependency, I get the following errors:

    Error: [$injector:unpr] Unknown provider: highlightFilterProvider <- highlightFilter
    ...
    Error: [$injector:unpr] Unknown provider: whereFilterProvider <- whereFilter

Which (**undocumented**) dependencies are those?

**Comment by benoror** [comment]
Apparently **highlightFilter** is just a filter to add a `highlight` class to a text, so I crafted it myself.

But what about **whereFilter**? I found the offending code to be:

    <div class="form-group ng-scope" ng-class="{'has-error': hasError(), 'has-success': hasSuccess(), 'has-feedback': form.feedback !== false}" ng-init="select_models=(form.schema.items | where : {value: model['Combobox']})">

What does that **where** filter do exactly? Why is it needed?

Thanks for your patience!

**Comment by stevehu** [comment]
Have you looked at the index.html and bower.json? And you can check my repo
and gulp webserver.

**Comment by benoror** [comment]
Looks like I totally forgot about **ui.sortable** filters, sorry and thanks!
